server:
  port: 8083
logging:
  level:
    com.github.budwing.obo: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,metrics

spring:
  application:
    name: obo-payment
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/paymentdb?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql

  cloud:
    alibaba.seata:
      tx-service-group: payment-service
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: classpath:flow.json
            rule-type: flow
    stream:
      kafka:
        binder:
          brokers: localhost
          default-broker-port: 9092
      bindings:
        payment-out-0:
          destination: payment-result
          use-native-encoding: true

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  service:
    vgroup-mapping:
      payment-service: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  client:
    undo:
      log-serialization: kryo