server:
  port: 8084
logging:
  level:
    com.github.budwing.obo: DEBUG

spring:
  application:
    name: obo-schedule
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/obo?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  cloud:
    alibaba.seata:
      tx-service-group: schedule-service

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: classpath:degraderule.json
            rule-type: degrade

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true

feign:
  sentinel:
    enabled: true

seata:
  enabled: true
  service:
    vgroup-mapping:
      schedule-service: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  client:
    undo:
      log-serialization: kryo
