server:
  port: 8084

spring:
  datasource:
    username: obo
    password: obo
    url: jdbc:h2:mem:scheduledb
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      sql:
        init:
          mode: ALWAYS
          data: classpath:data.sql
          schema: classpath:schema.sql

  cloud:
    discovery:
      client:
        simple:
          instances:
            obo-cinema:
              - uri: http://localhost:8081
              - uri: http://localhost:8091

logging:
  level:
    com.github.budwing.obo: DEBUG