server:
  port: 8084
logging:
  level:
    com.github.budwing.obo: DEBUG

spring:
  application:
    name: obo-schedule
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/scheduledb?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: obo
#    password: obo
#    url: jdbc:h2:mem:scheduledb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#    driver-class-name: org.h2.Driver
#  h2:
#    console.enabled: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  cloud:
    alibaba.seata:
      tx-service-group: schedule-service

# the default url is localhost:8761, so the following config is not necessary
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowType: TIME_BASED
  instances:
    CinemaClientgetSeatOfIntegerInteger:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 100
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: false

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true

seata:
  enabled: true
  service:
    vgroup-mapping:
      schedule-service: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  client:
    undo:
      log-serialization: kryo
