server:
  port: 8085

spring:
  datasource:
    username: obo
    password: obo
    url: jdbc:h2:mem:tradedb
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true

logging:
  level:
    com.github.budwing.obo: DEBUG