server:
  port: 8085
logging:
  level:
    com.github.budwing.obo: DEBUG

spring:
  application:
    name: obo-trade
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tradedb?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: obo
#    password: obo
#    url: jdbc:h2:mem:tradedb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#    driver-class-name: org.h2.Driver
#  h2:
#    console.enabled: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  cloud:
    alibaba.seata:
      tx-service-group: trade-service

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  service:
    vgroup-mapping:
      trade-service: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  client:
    undo:
      log-serialization: kryo