server:
  port: 8082
logging:
  level:
    com.github.budwing.obo: DEBUG

spring:
  datasource:
    username: obo
    password: obo
    url: jdbc:h2:mem:moviedb
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true

# the default url is localhost:8761, so the following config is not necessary
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/