server:
  port: 8081
logging:
  level:
    com.github.budwing.obo: DEBUG
  file:
    name: ${USERPROFILE}/logs/obo-cinema.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 2
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,metrics

spring:
  application:
    name: obo-cinema

  sql:
    init:
      mode: ALWAYS
      data: classpath:data.sql
      schema: classpath:schema.sql

  shardingsphere:
    datasource:
      names: cinemadb
      cinemadb:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/cinemadb?useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
    rules:
      sharding:
        tables:
          obo_hall:
            actual-data-nodes: cinemadb.obo_hall_$->{0..4}
            table-strategy:
              standard:
                sharding-column: cinema_id
                sharding-algorithm-name: obo-hall-inline
          obo_seat:
            actual-data-nodes: cinemadb.obo_seat_$->{0..4}
            table-strategy:
              standard:
                sharding-column: cinema_id
                sharding-algorithm-name: obo-seat-inline
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        binding-tables:
          - obo_hall,obo_seat
        broadcastTables:
          - obo_cinema
        sharding-algorithms:
          obo-hall-inline:
            type: INLINE
            props:
              algorithm-expression: obo_hall_$->{cinema_id % 5}
          obo-seat-inline:
            type: INLINE
            props:
              algorithm-expression: obo_seat_$->{cinema_id % 5}
        key-generators:
          snowflake:
            type: snowflake
    props:
      sql-show: true
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: classpath:flow.json
            rule-type: flow

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true
