server:
  port: 8081

spring:
  datasource:
    username: obo
    password: obo
    url: jdbc:h2:mem:cinemadb
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: ALWAYS
      data: classpath:data.sql
      schema: classpath:schema.sql

logging:
  level:
    com.github.budwing.obo: DEBUG