insert into obo_cinema(city,province,street,latitude,longitude,name,telephone) values('上海', '上海', '宝山区聚丰园路55号', 31.32, 121.39, '宝山区聚丰园路55号', '021661226xx');
insert into obo_hall(name,status,type,cinema_id) values('一号厅','OK','IMAX',1);
-- row 1
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,1, 1,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,2, 1,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,3, 1,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,4, 1,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,5, 1,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,6, 1,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,7, 1,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,8, 1,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,9, 1,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,10,1,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,11,1,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,12,1,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,13,1,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,14,1,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,15,1,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,16,1,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,17,1,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,18,1,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,19,1,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,20,1,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,21,1,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,22,1,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,23,1,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,1,24,1,24,'common',1,1);
-- row 2
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,1, 2,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,2, 2,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,3, 2,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,4, 2,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,5, 2,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,6, 2,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,7, 2,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,8, 2,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,9, 2,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,10,2,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,11,2,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,12,2,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,13,2,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,14,2,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,15,2,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,16,2,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,17,2,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,18,2,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,19,2,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,20,2,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,21,2,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,22,2,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,23,2,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,2,24,2,24,'common',1,1);
-- row 3
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,1, 3,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,2, 3,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,3, 3,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,4, 3,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,5, 3,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,6, 3,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,7, 3,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,8, 3,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,9, 3,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,10,3,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,11,3,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,12,3,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,13,3,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,14,3,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,15,3,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,16,3,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,17,3,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,18,3,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,19,3,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,20,3,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,21,3,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,22,3,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,23,3,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,3,24,3,24,'common',1,1);
-- row 4
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,1, 4,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,2, 4,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,3, 4,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,4, 4,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,5, 4,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,6, 4,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,7, 4,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,8, 4,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,9, 4,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,10,4,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,11,4,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,12,4,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,13,4,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,14,4,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,15,4,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,16,4,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,17,4,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,18,4,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,19,4,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,20,4,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,21,4,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,22,4,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,23,4,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,4,24,4,24,'common',1,1);
-- row 5
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,1, 5,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,2, 5,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,3, 5,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,4, 5,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,5, 5,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,6, 5,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,7, 5,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,8, 5,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,9, 5,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,10,5,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,11,5,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,12,5,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,13,5,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,14,5,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,15,5,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,16,5,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,17,5,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,18,5,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,19,5,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,20,5,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,21,5,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,22,5,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,23,5,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,5,24,5,24,'common',1,1);
-- row 6
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,1, 6,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,2, 6,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,3, 6,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,4, 6,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,5, 6,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,6, 6,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,7, 6,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,8, 6,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,9, 6,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,10,6,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,11,6,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,12,6,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,13,6,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,14,6,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,15,6,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,16,6,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,17,6,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,18,6,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,19,6,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,20,6,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,21,6,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,22,6,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,23,6,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,6,24,6,24,'common',1,1);
-- row 7
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,1, 7,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,2, 7,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,3, 7,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,4, 7,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,5, 7,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,6, 7,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,7, 7,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,8, 7,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,9, 7,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,10,7,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,11,7,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,12,7,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,13,7,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,14,7,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,15,7,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,16,7,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,17,7,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,18,7,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,19,7,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,20,7,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,21,7,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,22,7,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,23,7,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,7,24,7,24,'common',1,1);
-- row 8
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,1, 8,1, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,2, 8,2, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,3, 8,3, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,4, 8,4, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,5, 8,5, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,6, 8,6, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,7, 8,7, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,8, 8,8, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,9, 8,9, 'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,10,8,10,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,11,8,11,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,12,8,12,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,13,8,13,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,14,8,14,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,15,8,15,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,16,8,16,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,17,8,17,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,18,8,18,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,19,8,19,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,20,8,20,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,21,8,21,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,22,8,22,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,23,8,23,'common',1,1);
insert into obo_seat(available,hall_floor,seat_col,seat_row,coordinatex,coordinatey,type,cinema_id,hall_id) values(true,1,8,24,8,24,'common',1,1);