server:
  port: 8080
logging:
  level:
    com.github.budwing.obo: DEBUG
  file:
    name: ${USERPROFILE}/logs/obo-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 2
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,metrics

spring:
  application:
    name: obo-gateway
  cloud:
    gateway:
      routes:
        - id: obo-cinema
          uri: lb://obo-cinema
          predicates:
            - Path=/obo/cinema/**
        - id: obo-movie
          uri: http://localhost:8082
          predicates:
            - Path=/obo/movie/**
          filters:
            - CircuitBreaker=cinema-circuitbreaker
        - id: obo-payment
          uri: lb://obo-payment
          predicates:
            - Path=/obo/payment/**
        - id: obo-schedule
          uri: lb://obo-schedule
          predicates:
            - Path=/obo/schedule/**,/obo/ticket/**
        - id: obo-trade
          uri: lb://obo-trade
          predicates:
            - Path=/obo/order/**
        - id: obo-id-center
          uri: lb://obo-id-center
          predicates:
            - Path=/obo/id/**
  main:
    web-application-type: reactive

resilience4j.circuitbreaker:
  instances:
    cinema-circuitbreaker:
      registerHealthIndicator: true
      slidingWindowSize: 2
      permittedNumberOfCallsInHalfOpenState: 1
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 5s
      failureRateThreshold: 50